# -*- coding: utf-8 -*-
"""Handling missing values in python using simple imputers.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13WbDBTuZ42tw1GNoKeQik4NquvidX_s3
"""

import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer

df = pd.read_csv('student_performance_updated_1000.csv')

df.head()

df.shape

df.info()

imp_median = SimpleImputer(strategy="median")
imp_median.fit_transform(df[['AttendanceRate']])

imp_mode = SimpleImputer(strategy="most_frequent")
imp_mode.fit_transform(df[['Gender']])

imp_constant = SimpleImputer(strategy = 'constant',fill_value=13)

imp_constant.fit_transform(df[['StudyHoursPerWeek']])