# -*- coding: utf-8 -*-
"""How to build KNN model in Scikit-learn.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xiamq3iIYGbU1x_vFW2Yyyhu5AYh2eUa

Importing the dependencies
"""

import pandas as pd
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsRegressor
from sklearn.preprocessing import OneHotEncoder
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

df = pd.read_csv("student_performance_updated_1000.csv")

df.head()

# Move FinalGrade to last column
cols = [col for col in df.columns if col != "FinalGrade"] + ["FinalGrade"]
df = df[cols]

print(df.columns)

df

df.shape

df.info()

df.isnull().sum()

df = df.dropna()

df.isnull().sum()

df = df.drop("Name", axis=1)

from scipy.spatial import transform
Ohe = OneHotEncoder(handle_unknown="ignore",sparse_output=False).set_output(transform='pandas') #converting the categorical data to numeric

ohetransform = Ohe.fit(df[['Gender','ParentalSupport']])

ohetransform

# Convert 'Online Classes Taken' to numeric (0 or 1)
df['Online Classes Taken'] = df['Online Classes Taken'].astype(int)

# One-hot encode 'Gender' and 'ParentalSupport'
df_encoded_cols = ohetransform.transform(df[['Gender','ParentalSupport']])

# Concatenate the one-hot encoded columns and drop the original categorical columns
df = pd.concat([df, df_encoded_cols], axis=1).drop(['Gender','ParentalSupport'], axis=1)

X = df.drop("FinalGrade", axis=1)
y = df["FinalGrade"]

print(X.columns)

print(y)

"""Train test split"""

X_train, X_test, Y_train, Y_test = train_test_split(X, y, test_size=0.2, random_state=42)

"""Normalized Scaling"""

scaler = MinMaxScaler(feature_range=(0,1))

X_train = scaler.fit_transform(X_train)

X_test = scaler.fit_transform(X_test)

knn = KNeighborsRegressor(n_neighbors=8)

knn.fit(X_train, Y_train)

y_pred = knn.predict(X_test)

print(y_pred)

knn.score(X_test, Y_test)