# -*- coding: utf-8 -*-
"""Multicollinearity in Machine Learning .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MBCHoLgSH2uqUFXI2NveF0q9xAUjoCTF
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from statsmodels.stats.outliers_influence import variance_inflation_factor
from sklearn.decomposition import PCA
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression, Ridge
from sklearn.metrics import mean_squared_error
import sklearn.metrics # Import the module itself
from numpy.linalg import eig

np.random.seed(73)

num_player = 200

batting_average = np.random.normal(0.28,0.05,num_player)

batting_average = np.clip(batting_average, 0.2,0.4)

AB = np.random.randint(300,700,num_player)

H = AB * batting_average

Height = np.random.normal(72,6,num_player)

Wind = np.random.uniform(-1.5,1.5,num_player)

RBIs = (H * 0.5,) + (AB * 0.02) + (Wind * 7) + np.random.normal(0,10,num_player)

RBIs_rounded = np.round(RBIs)

H_rounded = np.round(H)

AB_rounded = np.round(AB)

data = pd.DataFrame ({
    'AB': AB_rounded,
    'H': H_rounded,
    'Height': Height,
    'Wind': Wind,
    'RBIs': RBIs_rounded.flatten()
})

data.head(10)

data.shape

#Fitting the regression model addressing the mulitcollinearity
X = data[['AB','H','Height','Wind']]
y = data['RBIs']

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

lr = LinearRegression()

lr.fit(X_train,y_train)

y_pred = lr.predict(X_test)

mse_before = mean_squared_error(y_test,y_pred)

mse_before

r2_score_initial = sklearn.metrics.r2_score(y_test, y_pred)
print("R2 Score:", r2_score_initial)

#Correlation Matrix

correlation_matrix = data.corr()

sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm',fmt=".2f")
plt.title('Correlation Matrix')
plt.show()

#VIF (Variance Inflation Factor)

vif_data = pd.DataFrame()

vif_data["feature"] = X.columns

vif_data["VIF"] = [variance_inflation_factor(X.values, i) for i in range(X.shape[1])]

print(vif_data)

#Condition index

normalized_features = (X - X.mean()) / X.std()

cov_matrix = np.cov(normalized_features)

eigenvalue, _ = np.linalg.eig(cov_matrix)

condition_indices = np.sqrt(eigenvalue.max() / eigenvalue)

ci_data = pd.DataFrame({
    'Condition Index': condition_indices
})

print(ci_data)

#Dropping a feature

X_reduced = X[['H',"Height", 'Wind']]

#Looking at correlation matrix

correlation_matrix = X_reduced.corr()

sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm',fmt=".2f")
plt.title('Correlation Matrix 2')
plt.show()

#VIF
vif_data_2 = pd.DataFrame()

vif_data_2['Features'] = X_reduced.columns

vif_data_2['VIP'] = [variance_inflation_factor(X_reduced.values, i) for i in range(X_reduced.shape[1])]

print(vif_data_2)

Lr_reduced = LinearRegression()

Lr_reduced.fit(X_train[['H','Height','Wind']], y_train)

y_pred_reduced = Lr_reduced.predict(X_test[['H','Height','Wind']])

mse_reduced = mean_squared_error(y_test, y_pred_reduced)

mse_reduced

r2_score_reduced = sklearn.metrics.r2_score(y_test, y_pred_reduced)

r2_score_reduced

#performing PCA

pca = PCA(n_components=3)

X_train_PCA = pca.fit_transform(X_train)

X_test_pca = pca.transform(X_test)

lr_PCA = LinearRegression()

print(f"Type of X_train_PCA: {type(X_train_PCA)}")
print(f"Shape of X_train_PCA: {X_train_PCA.shape}")
lr_PCA.fit(X_train_PCA,y_train)

y_pred_PCA = lr_PCA.predict(X_test_pca)

mse_pca = mean_squared_error(y_test, y_pred_PCA)

r2 = sklearn.metrics.r2_score(y_test, y_pred_PCA)

r2

mse_pca

#ridge Regression

ridge = Ridge(alpha=1.0)

ridge.fit(X_train,y_train)

y_pred_ridge = ridge.predict(X_test)

mse = mean_squared_error(y_test,y_pred_ridge)

mse

r2 = sklearn.metrics.r2_score(y_test,y_pred_ridge)

r2