# -*- coding: utf-8 -*-
"""OneHot encoder  with Python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mc5zIlh1r4XTurt7NSc48I1k5bD8GBEk

OneHot encoder is good for catergorical columns
"""

import pandas as pd

house = pd.read_csv("kc_house_data.csv")

house.head()

house['bedrooms'].unique()

from sklearn.preprocessing import OneHotEncoder

ohe = OneHotEncoder(handle_unknown='ignore',sparse_output=False).set_output(transform='pandas')

ohetransform = ohe.fit_transform(house[['bedrooms']])

ohetransform

df = pd.concat([house,ohetransform],axis=1)

df