# -*- coding: utf-8 -*-
"""Ordinal Encoder with python ML.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S2RuqwIUz8oPbMeUfElEd0mg3lmP4yeu

Ordinal encoder changes the categorial data into numbers
"""

import pandas as pd

df = pd.read_csv('student_performance_updated_1000.csv')

df.head()

df['Gender'].unique()

genders = ['Male', 'Female']

from sklearn.preprocessing import OrdinalEncoder

enc = OrdinalEncoder(categories=[genders])

# Calculate the mode of the 'Gender' column
gender_mode = df['Gender'].mode()[0]

# Fill NaN values in 'Gender' with the calculated mode
df['Gender'] = df['Gender'].fillna(gender_mode)

# Now, fit_transform the cleaned 'Gender' column and store the result
encoded_gender = enc.fit_transform(df[['Gender']])

# Print the first few encoded values to verify
print(encoded_gender[:5])