# -*- coding: utf-8 -*-
"""Python feature scaling.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nQ6PDB6CvU1QiuqI6VtJwRwo1YhM2N96
"""

import pandas as pd

housing_price = pd.read_csv('kc_house_data.csv')

housing_price.head()

housing_price.describe().round(3)

#Standardizing

X1 = housing_price.iloc[:, 3:]
X2 = housing_price['price']

print(X1)

from sklearn.preprocessing import StandardScaler

"""Standardization = X-mean(X)/std"""

scaler = StandardScaler()

X_1 = scaler.fit_transform(X1)

X_11 = pd.DataFrame(X_1, columns=X1.columns)

X_11.head()

"""Normalizatin

Normalization = X - min(x) / std
"""

from sklearn.preprocessing import MinMaxScaler

scaleMinMax = MinMaxScaler()

X_2 = scaleMinMax.fit_transform(X1)

X_22 = pd.DataFrame(X_2, columns=X1.columns)

X_22.head()