# -*- coding: utf-8 -*-
"""Simplied data preprocessing with python column transformer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vfNeoWhTy-TpIxQAbWaG0Rmbh_jnnlil
"""

#Make Column Transformer

import pandas as pd

df = {'Sales':[1000,495,555,640,840],
      'city':['Colombo','Jaffna','Ella','Hatton','Norwood'],
      'Size':[6,8,10,12,14]

      }

data = pd.DataFrame(df)

data

from sklearn.preprocessing import OneHotEncoder, OrdinalEncoder

ohe = OneHotEncoder(sparse_output=False)
ode = OrdinalEncoder()

from sklearn.compose import make_column_transformer

ct = make_column_transformer(
    (ohe,['city']),
    (ode,['Size']),
    remainder='passthrough'
)

ct.set_output(transform='pandas')

df_pandas = ct.fit_transform(data)

df_pandas

ct2 = make_column_transformer(
    (ohe,['city']),
    (ode,['Size']),
    remainder='drop'
)

ct2.set_output(transform='pandas')

df_pandas2 = ct2.fit_transform(data)

df_pandas2

ct3 = make_column_transformer(
    (ohe,['city']),
    ('passthrough',['Size']),
    remainder='drop'
)

ct3.set_output(transform='pandas')

df_ct3 = ct3.fit_transform(data)

df_ct3