# -*- coding: utf-8 -*-
"""Train_Test_Split.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WOBeHE20G30kOaCT1P5SBe_R1mou05Gi
"""

import pandas as pd
from sklearn.model_selection import train_test_split

house_price = pd.read_csv('kc_house_data.csv')

house_price.head()

x = house_price.drop(columns=['price'],axis=1)
y = house_price['price']

X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

print(X_train.shape)
print(X_test.shape)

X_train.describe()